package unisinu.desarrollo1.mvg.guia31;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author miler vargas mola 87223
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    BotonContador btnBotonA;
    BotonContador btnBotonB;
    BotonContador btnBotonC;
    JTextField txtReul;
    
    /**
     * Creates new form Main
     */
    public VentanaPrincipal() {
        initComponents();
        creacionVentana();
    }

    public void creacionVentana() {

        this.setTitle("Ejercicio de Herencia");
        this.setSize(250, 300);

        btnBotonA = new BotonContador();
        btnBotonA.setText("Boton A");
        btnBotonA.setBounds(10, 10, 100, 30);
        this.getContentPane().add(btnBotonA);

        btnBotonB = new BotonContador();
        btnBotonB.setText("Boton B");
        btnBotonB.setBounds(130, 10, 100, 30);
        this.getContentPane().add(btnBotonB);
        
        btnBotonC = new BotonContador();
        btnBotonC.setText("Iniciar");
        btnBotonC.setBounds(130, 130, 100, 30);
        this.getContentPane().add(btnBotonC);
        
        txtReul = new JTextField(20);
        txtReul.setBounds(10, 130, 120, 30);
        this.getContentPane().add(txtReul);

        btnBotonA.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                pulsacionBotonA(evt);
            }
        });

        btnBotonB.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                pulsacionBotonB(evt);
            }
        });
        btnBotonC.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                pulsacionBotonC(evt);
            }
        });
    }

    public void pulsacionBotonA(ActionEvent evt) {
        btnBotonA.incrementa();
    }

    public void pulsacionBotonB(ActionEvent evt) {
        btnBotonB.incrementa();
    }
    public void pulsacionBotonC(ActionEvent evt) {
        btnBotonC.incrementa();
        txtReul.setText(""+btnBotonC.getPulsaciones());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReiniciar = new javax.swing.JButton();
        btnVerPulsacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        btnVerPulsacion.setText("Ver Pulsacion");
        btnVerPulsacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPulsacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVerPulsacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerPulsacion)
                    .addComponent(btnReiniciar))
                .addGap(136, 136, 136))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed

        btnBotonA.reiniciar();
        btnBotonB.reiniciar();
        btnBotonC.reiniciar();
        txtReul.setText("");
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnVerPulsacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPulsacionActionPerformed

        String info;
        info = "El botón A se ha pulsado " + btnBotonA.getPulsaciones()+"\n";
        info += "El botón B se ha pulsado " + btnBotonB.getPulsaciones()  + "\n";
        info += "El botón C se ha pulsado " + btnBotonC.getPulsaciones()  + "\n";
        
        JOptionPane.showMessageDialog(null,info);

    }//GEN-LAST:event_btnVerPulsacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnVerPulsacion;
    // End of variables declaration//GEN-END:variables
}
